version: "3.7"
services:
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - 27017:27017
  app:
    container_name: app
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
      - DB_NAME=${DB_NAME}
      - MONGO_URL_DOCKER=${MONGO_URL_DOCKER}
      - MONGO_URL_DEV=${MONGO_URL_DEV}
      - SECRET_KEY=${SECRET_KEY}
      - VIACEP_BASE_URI=${VIACEP_BASE_URI}
      - FILE_MOVIES_DATA=${FILE_MOVIES_DATA}
      - FILE_MOVIES_RATINGS_DATA=${FILE_MOVIES_RATINGS_DATA}
    ports:
      - 3333:3333
    external_links:
      - mongo
    depends_on:
      - mongo
  migration:
    build:
      context: .
    command: node dist/migration.js
    volumes:
      - .:/app
    depends_on:
      - mongo
volumes:
  mongo-data:
    driver: local
